development: &default
  adapter: postgresql
  username: postgres
  password: postgres
  min_messages: warning
  database: dddd_development
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: dddd_test
